# Newsletter suggestions generated by ChatGPT based on the categories (e.g., current events)
# Names and links were updated as needed

newsletter_data = [
    {
        "Current Events": {
            "The Skimm": "https://www.theskimm.com/newsletters",
            "The Morning Brew": "https://www.morningbrew.com/daily",
            "Axios AM": "https://www.axios.com/newsletters/axios-am",
            "BBC News Daily Email": "https://www.bbc.co.uk/newsletters/bbcnewsemails/zhp28xs",
            "The Economist Espresso": "https://www.economist.com/newsletters",
        }
    },
    {
        "Finance and Markets": {
            "Financial Times' FirstFT": "https://www.ft.com/newsletters",
            "Bloomberg's Five Things": "https://www.bloomberg.com/account/newsletters",
            "The Motley Fool": "https://www.fool.com/",
            "MarketWatch's Need to Know": "https://www.marketwatch.com/newsletters",
            "The Wall Street Journal's What's News": "https://www.wsj.com/newsletters/whats-news",
        }
    },
    {
        "Food and Agriculture": {
            "Modern Farmer": "https://modernfarmer.com/category/news/",
            "Food Tank": "https://foodtank.com/sign-up/",
            "Civil Eats": "https://civileats.com/newsletter/",
            "AgFunderNews": "https://agfunder.com/newsletter",
            "EcoWatch Food and Water": "https://www.ecowatch.com/st/subscribe",
        }
    },
    {
        "Sustainability and the Environment": {
            "GreenBiz": "https://www.greenbiz.com/newsletters-subscribe",
            "World Economic Forum's Agenda": "https://weforum.us3.list-manage.com/subscribe/?u=6308fe51b420dc9ff3834abc8&id=bf3fa00e64",
            "Earth911": "https://earth911.com/subscribe/",
            "Sierra Club Insider": "https://www.sierraclub.org/sierra-club-email/insider",
            "Grist": "https://grist.org/subscribe/",
        }
    },
    {
        "Science": {
            "Nature Briefing": "https://briefer.public.springernature.app/nature_briefing?brieferEntryPoint=nb_nature_briefing",
            "Science News": "https://www.sciencenews.org/newsletters",
            "Scientific American Newsletter": "https://www.scientificamerican.com/newsletter-signup/",
            "The New York Times - Science Times": "https://www.nytimes.com/newsletters/signup/SC",
            "Wired Science Newsletter": "https://www.wired.com/newsletter/science"
        }
    },
    {
        "Health and Medicine": {
            "Harvard HealthBeat": "https://www.health.harvard.edu/healthbeat",
            "Mayo Clinic Health Letter": "https://mcpress.mayoclinic.org/product/healthletter/",
            "WebMD Daily": "https://member.webmd.com/subscribe",
            "The Lancet": "https://www.thelancet.com/journals/lancet/subscribe",
            "NIH News in Health": "https://newsinhealth.nih.gov/subscribe"
        }
    },
    {
        "Education": {
            "EdSurge": "https://www.edsurge.com/newsletters",
            "Inside Higher Ed": "https://www.insidehighered.com/newsletters",
            "Education Week": "https://www.edweek.org/newsletters/",
            "The Chronicle of Higher Education": "https://www.chronicle.com/account/get-newsletters",
            "MindShift": "https://www.kqed.org/mindshift",
        }
    },
]

categories_and_index = {
    "Current Events": 0,
    "Finance and Markets": 1,
    "Food and Agriculture": 2,
    "Sustainability and the Environment": 3,
    "Science": 4,
    "Health and Medicine": 5,
    "Education": 6
}
